/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DisplayNomorRouteImport } from './routes/display-nomor'
import { Route as DisplayPesananRouteImport } from './routes/display-pesanan'
import { Route as KasirRouteImport } from './routes/kasir'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProdukRouteImport } from './routes/produk'
import { Route as TransaksiRouteImport } from './routes/transaksi'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayNomorRoute = DisplayNomorRouteImport.update({
  id: '/display-nomor',
  path: '/display-nomor',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayPesananRoute = DisplayPesananRouteImport.update({
  id: '/display-pesanan',
  path: '/display-pesanan',
  getParentRoute: () => rootRouteImport,
} as any)
const KasirRoute = KasirRouteImport.update({
  id: '/kasir',
  path: '/kasir',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukRoute = ProdukRouteImport.update({
  id: '/produk',
  path: '/produk',
  getParentRoute: () => rootRouteImport,
} as any)
const TransaksiRoute = TransaksiRouteImport.update({
  id: '/transaksi',
  path: '/transaksi',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/display-nomor': typeof DisplayNomorRoute
  '/display-pesanan': typeof DisplayPesananRoute
  '/kasir': typeof KasirRoute
  '/login': typeof LoginRoute
  '/produk': typeof ProdukRoute
  '/transaksi': typeof TransaksiRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/display-nomor': typeof DisplayNomorRoute
  '/display-pesanan': typeof DisplayPesananRoute
  '/kasir': typeof KasirRoute
  '/login': typeof LoginRoute
  '/produk': typeof ProdukRoute
  '/transaksi': typeof TransaksiRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/display-nomor': typeof DisplayNomorRoute
  '/display-pesanan': typeof DisplayPesananRoute
  '/kasir': typeof KasirRoute
  '/login': typeof LoginRoute
  '/produk': typeof ProdukRoute
  '/transaksi': typeof TransaksiRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/display-nomor'
    | '/display-pesanan'
    | '/kasir'
    | '/login'
    | '/produk'
    | '/transaksi'
    | '/admin/dashboard'
    | '/admin/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/display-nomor'
    | '/display-pesanan'
    | '/kasir'
    | '/login'
    | '/produk'
    | '/transaksi'
    | '/admin/dashboard'
    | '/admin/login'
  id:
    | '__root__'
    | '/'
    | '/display-nomor'
    | '/display-pesanan'
    | '/kasir'
    | '/login'
    | '/produk'
    | '/transaksi'
    | '/admin/dashboard'
    | '/admin/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DisplayNomorRoute: typeof DisplayNomorRoute
  DisplayPesananRoute: typeof DisplayPesananRoute
  KasirRoute: typeof KasirRoute
  LoginRoute: typeof LoginRoute
  ProdukRoute: typeof ProdukRoute
  TransaksiRoute: typeof TransaksiRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display-nomor': {
      id: '/display-nomor'
      path: '/display-nomor'
      fullPath: '/display-nomor'
      preLoaderRoute: typeof DisplayNomorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display-pesanan': {
      id: '/display-pesanan'
      path: '/display-pesanan'
      fullPath: '/display-pesanan'
      preLoaderRoute: typeof DisplayPesananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasir': {
      id: '/kasir'
      path: '/kasir'
      fullPath: '/kasir'
      preLoaderRoute: typeof KasirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk': {
      id: '/produk'
      path: '/produk'
      fullPath: '/produk'
      preLoaderRoute: typeof ProdukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaksi': {
      id: '/transaksi'
      path: '/transaksi'
      fullPath: '/transaksi'
      preLoaderRoute: typeof TransaksiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DisplayNomorRoute: DisplayNomorRoute,
  DisplayPesananRoute: DisplayPesananRoute,
  KasirRoute: KasirRoute,
  LoginRoute: LoginRoute,
  ProdukRoute: ProdukRoute,
  TransaksiRoute: TransaksiRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
